spring.application.name=demo

# PostgreSQL Connection Settings
# DHAYAN DEIN: Yahan se double 'spring.datasource.url=' hata diya gaya hai
spring.datasource.url=jdbc:postgresql://localhost:5432/infonest
spring.datasource.username=postgres
spring.datasource.password=suhasini@123
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Settings
# Dialect specify karna ab zaroori nahi hai, Spring khud detect kar leta hai
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8081
spring.web.resources.static-locations=classpath:/static/

# JWT Configuration
infonest.jwt.secret=MySuperSecretKeyForInfoNestProject2025MakeItLonger
infonest.jwt.expiration=86400000

# Logging & Mail Settings
logging.level.org.springframework.security=DEBUG
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=singhsukirti375@gmail.com
spring.mail.password=dazx naak eqvt wvaj
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Upload Settings
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=5MB